In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

data = pd.read_csv('i-p.csv', index_col='Year')
data = data.fillna(0)
data

,Country,GDP (in USD),Population,GDP Growth Rate (%),Fertility Rate,"Infant Mortality Rate (per 1,000 live births)","Maternal Mortality Rate (per 100,000 live births)",Agricultural Output (in USD),Active Military Personnel,Reserve Military Personnel,Literacy Rate (%),IT Output (in USD),Number of Tanks,Number of Submarines,Number of Armoured Vehicles
Year,,,,,,,,,,,,,,,
2000,Israel,132.02 billion,"6,049,000",5.18,2.89,5.0,7.2,5.71 billion,"168,000","445,000",97.1,6.78 billion,"2,760",3.0,"10,760"
2000,Palestine,4.56 billion,"3,374,000",5.33,5.36,24.6,26.0,880 million,0,0,90.3,0.115 billion,0,0.0,0
2001,Israel,131.02 billion,"6,165,000",-0.47,2.89,4.8,6.7,5.17 billion,"166,500","445,000",97.5,6.89 billion,"2,791",3.0,"10,814"
2001,Palestine,4.59 billion,"3,400,000",-50.00,5.22,22.5,24.4,925 million,0,0,90.8,0.122 billion,0,0.0,0
2002,Israel,126.64 billion,"6,263,000",-0.35,2.98,4.6,5.9,4.76 billion,"163,000","375,000",97.9,7.02 billion,"2,821",3.0,"10,885"
2002,Palestine,4.34 billion,"3,421,000",-46.30,5.07,20.2,21.3,914 million,0,0,91.2,0.132 billion,0,0.0,0
2003,Israel,129.56 billion,"6,684,000",2.80,2.81,4.3,6.1,5.10 billion,"160,000","445,000",97.9,7.15 billion,"2,819",3.0,"10,885"
2003,Palestine,3.56 billion,"3,693,000",-16.10,5.15,23.0,30.9,819 million,0,0,91.7,0.143 billion,0,0.0,0
2004,Israel,143.53 billion,"6,830,000",4.50,2.84,4.1,6.8,5.33 billion,"159,000","428,000",97.9,7.36 billion,"2,798",3.0,"10,886"
2004,Palestine,3.89 billion,"3,791,000",10.50,4.95,21.6,29.4,876 million,0,0,92.1,0.154 billion,0,0.0,0
2005,Israel,155.05 billion,"6,925,000",4.97,2.87,3.9,6.4,5.38 billion,"156,000","411,000",98.4,7.69 billion,"2,771",3.0,"10,876"
2005,Palestine,4.13 billion,"3,890,000",7.60,4.78,19.7,28.1,927 million,0,0,92.5,0.165 billion,0,0.0,0
2006,Israel,179.02 billion,"7,112,000",4.60,2.87,3.8,6.1,5.48 billion,"176,500","438,000",97.8,6.90 billion,"2,760",3.0,"10,634"
2006,Palestine,4.47 billion,"3,762,000",5.80,4.14,18.6,25.4,929 million,0,0,91.9,0.230 billion,0,0.0,0
2007,Israel,195.35 billion,"7,295,000",4.90,2.90,3.7,5.9,5.60 billion,"179,900","436,000",97.8,7.20 billion,"2,760",3.0,"10,634"
2007,Palestine,4.96 billion,"3,865,000",5.30,4.07,17.6,24.3,978 million,0,0,0.0,0,0,0.0,0
2008,Israel,215.95 billion,"7,413,000",1.20,2.93,3.7,5.6,5.84 billion,"177,400","435,000",97.8,7.40 billion,"2,760",3.0,"10,634"
2008,Palestine,5.05 billion,"3,966,000",4.20,3.98,16.7,23.2,1.02 billion,0,0,0.0,0,0,0.0,0
2009,Israel,202.98 billion,"7,602,000",0.80,2.93,4.0,5.5,5.80 billion,"169,700","434,000",97.8,7.50 billion,"2,760",3.0,"10,634"
2009,Palestine,4.98 billion,"4,018,000",6.80,4.00,15.9,22.4,1.04 billion,0,0,0.0,0,0,0.0,0
2010,Israel,217.90 billion,"7,746,000",4.60,2.96,3.7,5.5,5.85 billion,"170,300","431,000",97.8,7.80 billion,"2,760",3.0,"10,634"
2010,Palestine,4.95 billion,"4,070,000",8.50,3.99,15.1,21.9,1.08 billion,0,0,0.0,0,0,0.0,0
2011,Israel,242.89 billion,"7,907,000",4.60,2.96,3.5,4.9,5.90 billion,"170,750","429,500",97.8,8.20 billion,"2,760",3.0,"10,634"
2011,Palestine,5.39 billion,"4,198,000",-0.50,3.87,14.3,21.1,1.12 billion,0,0,0.0,0,0,0.0,0
2012,Israel,254.94 billion,"8,081,000",3.30,2.99,3.3,4.7,5.97 billion,"171,450","428,000",97.8,8.60 billion,"2,760",5.0,"10,634"
2012,Palestine,5.65 billion,"4,297,000",5.90,3.83,13.8,20.4,1.15 billion,0,0,0.0,0,0,0.0,0
2013,Israel,272.18 billion,"8,192,000",3.30,3.01,3.2,4.6,6.02 billion,"174,550","424,750",97.8,9.00 billion,"2,760",5.0,"10,634"
2013,Palestine,5.69 billion,"4,404,000",4.90,3.79,13.4,20.0,1.17 billion,0,0,0.0,0,0,0.0,0
2014,Israel,291.03 billion,"8,299,000",3.60,3.02,3.1,4.3,6.07 billion,"177,350","421,500",97.8,9.30 billion,"2,760",5.0,"10,634"
2014,Palestine,5.71 billion,"4,530,000",5.90,3.74,12.8,19.5,1.20 billion,0,0,0.0,0,0,0.0,0
2015,Israel,309.01 billion,"8,431,000",2.60,3.03,3.0,4.1,6.09 billion,"176,500","418,500",97.8,9.60 billion,"2,760",5.0,"10,634"
2015,Palestine,5.87 billion,"4,692,000",3.30,3.69,12.3,18.9,1.23 billion,0,0,0.0,0,0,0.0,0
2016,Israel,321.57 billion,"8,548,000",4.00,3.06,2.9,3.8,6.10 billion,"176,500","415,000",97.8,10.00 billion,"2,760",5.0,"10,634"
2016,Palestine,5.93 billion,"4,768,000",4.00,3.64,11.9,18.5,1.26 billion,0,0,0.0,0,0,0.0,0
2017,Israel,348.70 billion,"8,712,000",3.40,3.06,2.8,3.7,6.16 billion,"174,500","410,000",97.8,10.70 billion,"2,760",5.0,"10,634"
2017,Palestine,6.00 billion,"4,816,000",3.10,3.57,11.4,17.9,1.29 billion,0,0,0.0,0,0,0.0,0
2018,Israel,370.12 billion,"8,972,000",3.50,3.06,2.7,3.6,6.20 billion,"170,000","405,000",97.8,11.20 billion,"2,760",5.0,"10,634"
2018,Palestine,6.10 billion,"4,857,000",0.90,3.53,11.0,17.5,1.32 billion,0,0,0.0,0,0,0.0,0
2019,Israel,395.53 billion,"9,136,000",3.40,3.06,2.6,3.5,6.22 billion,"169,500","399,000",97.8,11.70 billion,"2,760",5.0,"10,634"
2019,Palestine,6.09 billion,"4,895,000",1.00,3.48,10.6,17.1,1.35 billion,0,0,0.0,0,0,0.0,0
2020,Israel,375.82 billion,"9,227,000",-2.40,3.05,2.7,2.9,6.21 billion,"169,500","395,000",97.8,42.45 billion,"2,760",5.0,"10,634"
2020,Palestine,6.20 billion,"4,934,000",-7.70,3.46,10.3,16.7,1.37 billion,0,0,98.5,1.03 billion,0,0.0,0
2021,Israel,398.02 billion,"9,390,000",1.63,3.02,2.6,3.3,2.86 billion,"170,000","465,000",97.8,46.21 billion,"2,760",5.0,"10,634"
2021,Palestine,15.05 billion,"5,368,000",-11.40,3.24,12.6,15.2,352 million,0,0,98.6,1.10 billion,0,0.0,0

In [69]:
def clean(arg):
    
    arg = str(arg)
    
    if 'billion' in arg:
        ans = arg.strip('billion')
        ans = float(ans)
        return ans * 1e9
    
    if 'million' in arg:
        ans = arg.strip('million')
        ans = float(ans)
        return ans* 1e6
    
    if ',' in  arg:
        com = arg.replace(',', '')
        return float(com)
    
    else:
        return float(arg)


ff = '222,000,000,'

for a in data.drop('Country', axis=1):
    data[a] =  data[a].apply(clean)

data.tail()

,Country,GDP (in USD),Population,GDP Growth Rate (%),Fertility Rate,"Infant Mortality Rate (per 1,000 live births)","Maternal Mortality Rate (per 100,000 live births)",Agricultural Output (in USD),Active Military Personnel,Reserve Military Personnel,Literacy Rate (%),IT Output (in USD),Number of Tanks,Number of Submarines,Number of Armoured Vehicles
Year,,,,,,,,,,,,,,,
2019,Palestine,6.090000e+09,4895000.0,1.00,3.48,10.6,17.1,1.350000e+09,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0
2020,Israel,3.758200e+11,9227000.0,-2.40,3.05,2.7,2.9,6.210000e+09,169500.0,395000.0,97.8,4.245000e+10,2760.0,5.0,10634.0
2020,Palestine,6.200000e+09,4934000.0,-7.70,3.46,10.3,16.7,1.370000e+09,0.0,0.0,98.5,1.030000e+09,0.0,0.0,0.0
2021,Israel,3.980200e+11,9390000.0,1.63,3.02,2.6,3.3,2.860000e+09,170000.0,465000.0,97.8,4.621000e+10,2760.0,5.0,10634.0
2021,Palestine,1.505000e+10,5368000.0,-11.40,3.24,12.6,15.2,3.520000e+08,0.0,0.0,98.6,1.100000e+09,0.0,0.0,0.0

In [76]:
high_n = ['GDP (in USD)', 'Population', 'Agricultural Output (in USD)', 'Active Military Personnel', 'Reserve Military Personnel', 'IT Output (in USD)', 'Number of Tanks', 'Number of Armoured Vehicles']

isl, pls = data.groupby('Country')

isl = np.array(isl, dtype=object)

new_is = isl[1].drop('Country', axis=1)

pls = np.array(pls, dtype=object)

new_pl = pls[1].drop('Country', axis=1)

In [77]:
plt.figure(figsize=(19, 10))

# plot = new_is[ 'GDP (in USD)'].join(new_pl[ 'GDP (in USD)'], lsuffix='_Iseral', rsuffix='_Palestine')
# plot = new_pl.join(new_is, lsuffix='_pl', rsuffix='_is')

sb.heatmap(data=new_pl.drop(columns=high_n), annot=True)

plt.show()

KeyError: "['GDP (in USD)\\t'] not found in axis"